services:
  api-barbershop:
    image: barbershop-management
    ports:
      - "8080:8080"
    depends_on:
      db-postgres:
        condition: service_healthy
  db-postgres:
    image: postgres:latest
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: barbershop
    ports:
      - "5432:5432"